services:
  beatbot:
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./node_modules:/app/node_modules
    command: npm run dev
    stdin_open: true
    tty: true 