version: '3.8'
services:
  lavalink:
    image: fredboat/lavalink:f76cf9b-alpine
    networks:
      - bot_network
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    ports:
      - "2333:2333"

  beatbot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - LAVALINK_PASSWORD=youshallnotpass
      - LAVALINK_HOST=lavalink
      - LAVALINK_PORT=2333
      - NODE_ENV=production
    depends_on:
      - lavalink
    volumes:
      - ./data:/app/data
      - ./application.yml:/app/application.yml
    networks:
      - bot_network
    ports:
      - "3000:3000"

volumes:
  bot-data:

networks:
  bot_network:
    driver: bridge

